apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
    version: "${VERSION}"
spec:
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
        version: "${VERSION}"
    spec:
      containers:
        - name: portfolio
          image: rileywebdev/website-app:${VERSION}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "12m"
            limits:
              memory: "256Mi"
              cpu: "24m"
          ports:
            - containerPort: 80
          env:
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PORT
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASSWORD
            - name: FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FROM_EMAIL
            - name: TO_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TO_EMAIL
            - name: HCAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HCAPTCHA_SECRET
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
