apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: default
  annotations:
    # Where your TLS certs come from:
    cert-manager.io/cluster-issuer: "letsencrypt-production"

    # Tells K8s to use the NGINX ingress controller:
    kubernetes.io/ingress.class: "nginx"

    # Force HTTPS:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    # IMPORTANT for rewriting:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rileylitchfield.com
        - www.rileylitchfield.com
      secretName: portfolio-tls
  rules:
    - host: rileylitchfield.com
      http:
        paths:
          # Rewrite requests from /store/something -> /something
          - path: /store(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ecommerce-project
                port:
                  number: 80

          # Everything else goes to portfolio
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
